### ISSUE TITLE
Urgent: Few things outstanding to get to an A

### ISSUE THREAD

**Issue by sairafurqan** [ubco-W2022T2-data301/project-group-group62#2]
Hello,

I was going through your project and you have met all but two of the criteria for an A. One of the things is really easy, and the other one is slightly more involved. 

Here are the two things missing:

- [x] Issues aren't closed (though all the tasks are completed) ; effective use of issues requires all resolved issues to be closed.
- [x] Upon closer look, we haven't seen evidence of the "complex method chaining" criteria and you did not use .py file in any of your notebook.

> Complex method chaining
> - At least three advanced operations (for e.g anonymous or lambda functions in assign or apply functions)
> - At least two method chains

At the moment, we're leaning towards downgrading your project to an **B**, but if you can fix these things before April 24th, we can award you your contracted grade of an B.

Of course, you are more than welcome to just accept the **B**, but please let us know either way what you decide.

Thanks,

**Comment by wingfanx** [comment]
Hi Saira, thank you so much for the updates and the opportunity, we will try to add more stuff to the method chaining by April 24, and complete the tasks you listed above. I will let you know under this Issues once our repository is updated. Thank you.  
Besides, just wondering if there's a typo; if we completed the listed tasks above, will we still be able to get an A?

**Comment by wingfanx** [comment]
Hi Saira, my group and I have updated the method chaining now, thank you so much for the given opportunities.
